### ISSUE TITLE
Can't init project

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/llama-pack#118]
The `llama-pack init --manifest https://my-twa.com/manifest.json` command produce the following error:

`cli ERROR core_1.Config.loadOrCreate is not a function`

This is after updating to the latest `0.5.0` version.

**Comment by FluorescentHallucinogen** [comment]
Just tested, this is a regression in `0.5.0`, in `0.4.3` init works fine. I believe this is because #109.

**Comment by FluorescentHallucinogen** [comment]
@andreban @PEConn @NotWoods cc.

**Comment by andreban** [comment]
I can reproduce. Looking into it.

**Comment by andreban** [comment]
Apparently something went wrong while publishing. I rebuilt and re-published the same code as `v0.5.1`. Can you check if it works now?

**Comment by FluorescentHallucinogen** [comment]
Just tested, `init` and `update` works in `v0.5.1` like a charm! @andreban Thanks!
